#!/bin/bash
STUBS_DIR=$HOME/.stub/stubs
DOCKER_COMPOSE_STUB=$STUBS_DIR/docker-compose.yml.stub
CURRENT_COMPOSE="$(pwd)/docker-compose.yml"

if [ ! -f $DOCKER_COMPOSE_STUB ]; then
    echo "找不到 docker-compose.yml.stub"
    exit 1
else
    cp $DOCKER_COMPOSE_STUB $CURRENT_COMPOSE
fi

if [ $# -ge 1 ]; then

    # depends
    echo "        depends_on:" >> $CURRENT_COMPOSE
    for depend in $@
    do
        echo "            - ${depend}" >> $CURRENT_COMPOSE
    done

    # services
    for service in $@
    do
        cat "${STUBS_DIR}/${service}.stub" >> $CURRENT_COMPOSE
    done

    # volumes
    echo "volumes:" >> $CURRENT_COMPOSE
    for valume in $@
    do
        echo "    hom-${valume}:
        driver: local" >> $CURRENT_COMPOSE
    done
fi

echo "networks:
    hom:
        driver: bridge" >> $CURRENT_COMPOSE

echo ""
echo "已產生 docker-compose.yml"

echo ""
echo "install sail..."
echo ""

docker info > /dev/null 2>&1

# Ensure that Docker is running...
if [ $? -ne 0 ]; then
    echo "Docker is not running."

    exit 1
fi

docker run --rm \
    --pull=always \
    -v "$(pwd)":/opt \
    -w /opt \
    laravelsail/php81-composer:latest \
    bash -c "composer require laravel/sail --dev"

./vendor/bin/sail build

echo "Thank you!"
